"Id","ParentId","CommentBody","CreatedById","CreatedDate","LastModifiedDate","IsPublished","IsDeleted"
"00aQk000007i79pIAA","500Qk00000CQLbPIAX","Not possible to close due to error.
Error
Something is wrong
CaseTrigger: execution of AfterUpdate caused by: System.DmlException: Update failed.
First exception on row 0 with id 555Qk00000O1SJDIA3;
first error: CANNOT_INSERT_UPDATE_ACTIVATE_ENTITY,
CaseTrigger: execution of AfterUpdate caused by: System.DmlException: Update failed.
First exception on row 0 with id 001Qk000007ZmRtIAK;
first error: FIELD_CUSTOM_VALIDATION_EXCEPTION, 
Please add Distributor for this partner (""Reseller via Distributor""): [Distributor__c] 
Class.Helper.updateSkipTriggers: line 115, column 1 
Class.CaseTriggerHandler.postUpdateAccounts: line 1878, column 1 
Class.CaseTriggerHandler.executeAfterUpdate: line 312, column 1 
Class.TriggerHandlerBase.execute: line 45, column 1 
Class.TriggerHandlerBase.run: line 119, column 1 
Trigger.CaseTrigger: line 2, column 1: [] 
Class.CaseMilestoneHelper.completeMilestones: line 76, column 1 
Class.CaseTriggerHandler.completeMilestones: line 1495, column 1 
Class.CaseTriggerHandler.executeAfterUpdate: line 296, column 1 
Class.TriggerHandlerBase.execute: line 45, column 1 
Class.TriggerHandlerBase.run: line 119, column 1 Trigger.CaseTrigger: line 2, column 1","005Qk000001nViEIAU","2024-07-03T04:31:35.000Z","2024-07-03T04:31:35.000Z","false","false"
