"Id","CaseNumber","Ticket_Record_Type_Name__c","Subject","Description","DevOps_Steps_to_Reproduce__c","What_We_Know__c","Next_Steps__c","Solution_Comment__c","Issue_Type__c","Ticket_Owner_Name__c","Ticket_Type__c","Platform__c","Collector_Code__c","Feature__c","Product_Version__c","Build_Number__c","Age__c","Status","Account_Name__c","Contact_Name__c","CreatedDate","ClosedDate"
"500Qk00000EUvyXIAT","00418281","Support Ticket","FSAC Import Errors","Hi team

I have recently expanded my FSAC import jobs to include additional Isilon access zones in preparation for them to receive event data.

Most of them do not have any events yet however, I am seeing errors when the scheduled job runs over night.

The main error seems to be:

System.Exception: Abort received while retrying
   at Stealthbits.Common.Database.DatabaseUtils.RetryOnDeadlock[TResult](Func`1 query, Func`1 cancellationPending, Action retryDelay, Int32 maxRetries)
   at <a href='https://Stealthbits.StealthAUDIT.DataCollectors.FSAA' target='_blank'>Stealthbits.StealthAUDIT.DataCollectors.FSAA</a>.Import.Import.RetryOnDeadlock[TResult](Func`1 query)
   at <a href='https://Stealthbits.StealthAUDIT.DataCollectors.FSAA' target='_blank'>Stealthbits.StealthAUDIT.DataCollectors.FSAA</a>.Import.Import.DeleteTempTable(String tableName)
   at <a href='https://Stealthbits.StealthAUDIT.DataCollectors.FSAA' target='_blank'>Stealthbits.StealthAUDIT.DataCollectors.FSAA</a>.Import.Import.ImportData(TableDefinition definition, String tempTableName, ImportType importType, Object[,] parameters)
   at <a href='https://Stealthbits.StealthAUDIT.DataCollectors.FSAA' target='_blank'>Stealthbits.StealthAUDIT.DataCollectors.FSAA</a>.BulkImportTask.ImportTable(Import import, TableDefinition table, Int32 hostId, TimeSpan strucMapTime)
   at <a href='https://Stealthbits.StealthAUDIT.DataCollectors.FSAA' target='_blank'>Stealthbits.StealthAUDIT.DataCollectors.FSAA</a>.BulkImportTask.InternalProcessRecord()
   at <a href='https://Stealthbits.StealthAUDIT.DataCollectors.Tasks.Task' target='_blank'>Stealthbits.StealthAUDIT.DataCollectors.Tasks.Task</a>.StartExecute()

What could be causing this problem?

Regards","","","","put 6 hours as a command timeout parameter (360min) - Storage global settings","Guidance","Ilia Kudashev","","Netwrix Enterprise Auditor","StealthAUDIT General","Initial setup","11.5","","3.3","Closed - Resolved","Westpac Banking Corporation","Mark Chambers","2024-08-16T00:01:20.000Z","2024-08-19T07:39:30.000Z"
