"Id","CaseNumber","Ticket_Record_Type_Name__c","Subject","Description","DevOps_Steps_to_Reproduce__c","What_We_Know__c","Next_Steps__c","Solution_Comment__c","Issue_Type__c","Ticket_Owner_Name__c","Ticket_Type__c","Platform__c","Collector_Code__c","Feature__c","Product_Version__c","Build_Number__c","Age__c","Status","Account_Name__c","Contact_Name__c","CreatedDate","ClosedDate"
"500Qk00000KxAUVIA3","00433239","Support Ticket","Error when trying to scan new servers added to the environment","ERROR:
<a href='https://Stealthbits.StealthAUDIT.DataCollectors.FSAA' target='_blank'>Stealthbits.StealthAUDIT.DataCollectors.FSAA</a>.FSAAException: Unable to start scan: Could not initialize scan session for <a href='https://usilg01-fpp083.wrbts.ads.wrberkley.com' target='_blank'>usilg01-fpp083.wrbts.ads.wrberkley.com</a> with <a href='https://usilg01-app606.wrbts.ads.wrberkley.com' target='_blank'>usilg01-app606.wrbts.ads.wrberkley.com</a>
   at <a href='https://Stealthbits.StealthAUDIT.DataCollectors.FSAA' target='_blank'>Stealthbits.StealthAUDIT.DataCollectors.FSAA</a>.AccessScanTask.d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at <a href='https://Stealthbits.StealthAUDIT.DataCollectors.FSAA' target='_blank'>Stealthbits.StealthAUDIT.DataCollectors.FSAA</a>.AccessScanTask.InternalProcessRecord()
   at <a href='https://Stealthbits.StealthAUDIT.DataCollectors.Tasks.Task' target='_blank'>Stealthbits.StealthAUDIT.DataCollectors.Tasks.Task</a>.StartExecute()","","Hosts are showing an error stating they could not transfer certificate info. Awaiting log upload from Eric



--------
24/01/2025
--------
Certificate exchange is failing with the service account and falling back to the system account. 
The issue appears similar to 00422068, but in this case both the local system and service accounts are failing

22/01/2025 16:08:23	INFO	StealthAUDIT	THostConnection.GetOrderedSecurityMap	""Following credentials are preferred for the host usilg01-fpt011.wrbts.ads.wrberkley.com in profile ""StealthAUDIT Svc Acct"" : WRBTSsvc-bts-p-slb01 ""			-1	13180	14876
22/01/2025 16:08:23	DEBUG	FILESYSTEMACCESS	AccessScanTask	""Acquiring certificate exchange lock at D:StealthAUDITFSAAfsaa_certificate_exchange.lock""	usilg01-fpt011.wrbts.ads.wrberkley.com	DCExtract	13740	13180	14876
22/01/2025 16:08:23	DEBUG	FILESYSTEMACCESS	AccessScanTask	""Using certificate authority: Friendly Name = FSAA Certificate Authority 7/9/2024 10:37:52 AM, Thumbprint = 120676946BB74ECCCB5656104C484C57707A2E4C""	usilg01-fpt011.wrbts.ads.wrberkley.com	DCExtract	13740	13180	14876
22/01/2025 16:08:23	INFO	FILESYSTEMACCESS	AccessScanTask	""Failed to exchange certificates with running proxy service using task credentials, retrying with LocalSystem: Unable to establish secure stream for certificate exchange, requires trusted target domain""	usilg01-fpt011.wrbts.ads.wrberkley.com	DCExtract	13740	13180	14876
22/01/2025 16:08:23	DEBUG	FILESYSTEMACCESS	AccessScanTask	""Certificate exchange with running proxy service failed: Stealthbits.StealthAUDIT.DataCollectors.FSAA.Applet.Client.AppletClientException: Unable to establish secure stream for certificate exchange, requires trusted target domain ---> System.Security.Authentication.AuthenticationException: A call to SSPI failed, see inner exception. ---> System.ComponentModel.Win32Exception: The target principal name is incorrect     --- End of inner exception stack trace ---     at System.Net.Security.NegoState.StartSendAuthResetSignal(LazyAsyncResult lazyResult, Byte[] message, Exception exception)     at System.Net.Security.NegoState.StartSendBlob(Byte[] message, LazyAsyncResult lazyResult)     at System.Net.Security.NegoState.CheckCompletionBeforeNextSend(Byte[] message, LazyAsyncResult lazyResult)     at System.Net.Security.NegoState.ProcessReceivedBlob(Byte[] message, LazyAsyncResult lazyResult)     at System.Net.Security.NegoState.StartReceiveBlob(LazyAsyncResult lazyResult)     at System.Net.Security.NegoState.CheckCompletionBeforeNextReceive(LazyAsyncResult lazyResult)     at System.Net.Security.NegoState.StartSendBlob(Byte[] message, LazyAsyncResult lazyResult)     at System.Net.Security.NegoState.ProcessAuthentication(LazyAsyncResult lazyResult)     at System.Net.Security.NegotiateStream.AuthenticateAsClient(NetworkCredential credential, ChannelBinding binding, String targetName, ProtectionLevel requiredProtectionLevel,

--------
01/28/2025
--------
We changed the jobs to run with a specified service account instead of using the default and the issue appears to have resolved. The job is set back to use all hosts in the host list instead of just problem hosts and is running so we can check back in the morning to make sure the job succeeds.","Awaiting job to run overnight and verify the issue is resolved.","Issue:
New hosts are not scanning properly and recieving a certificate issue when attempting to authenticate.

Cause:
Default profile was not getting permissions and was falling back to system account.

Resolution:
Specified service account to use for the job.","Incorrect configuration: audit settings","Ian Ranstrom","Error","Netwrix Enterprise Auditor","StealthAUDIT for Windows File Systems","Credentials","11.6","","12.8","Closed - Resolved","W.R. Berkley Corporation","Eric Van Brocklibn","2025-01-22T21:23:57.000Z","2025-02-04T16:42:53.000Z"
