"Id","ParentId","Type","CreatedById","CreatedDate","Body","Title","LinkUrl","RelatedRecordId","InsertedById","LastModifiedDate"
"0D5Qk00000VLXAnKAP","500Qk00000KxAUVIA3","TextPost","0054u000008ARZjAAO","2025-01-22T21:23:58.000Z","Description: ERROR:
<a href='https://Stealthbits.StealthAUDIT.DataCollectors.FSAA' target='_blank'>Stealthbits.StealthAUDIT.DataCollectors.FSAA</a>.FSAAException: Unable to start scan: Could not initialize scan session for <a href='https://usilg01-fpp083.wrbts.ads.wrberkley.com' target='_blank'>usilg01-fpp083.wrbts.ads.wrberkley.com</a> with <a href='https://usilg01-app606.wrbts.ads.wrberkley.com' target='_blank'>usilg01-app606.wrbts.ads.wrberkley.com</a>
   at <a href='https://Stealthbits.StealthAUDIT.DataCollectors.FSAA' target='_blank'>Stealthbits.StealthAUDIT.DataCollectors.FSAA</a>.AccessScanTask.d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at <a href='https://Stealthbits.StealthAUDIT.DataCollectors.FSAA' target='_blank'>Stealthbits.StealthAUDIT.DataCollectors.FSAA</a>.AccessScanTask.InternalProcessRecord()
   at <a href='https://Stealthbits.StealthAUDIT.DataCollectors.Tasks.Task' target='_blank'>Stealthbits.StealthAUDIT.DataCollectors.Tasks.Task</a>.StartExecute()","","","","0054u000008ARZjAAO","2025-01-22T21:23:58.000Z"
"0D5Qk00000VQMzGKAX","500Qk00000KxAUVIA3","TextPost","005Qk000002AJWTIA4","2025-01-23T22:19:32.000Z","Next Steps Updated: Awaiting logs","","","","005Qk000002AJWTIA4","2025-01-23T22:19:32.000Z"
"0D5Qk00000VQMzFKAX","500Qk00000KxAUVIA3","TextPost","005Qk000002AJWTIA4","2025-01-23T22:19:32.000Z","What We've Learned Updated: Hosts are showing an error stating they could not transfer certificate info. Awaiting log upload from Eric","","","","005Qk000002AJWTIA4","2025-01-23T22:19:32.000Z"
"0D5Qk00000VSjNhKAL","500Qk00000KxAUVIA3","TextPost","005Qk000002AJWTIA4","2025-01-24T16:08:54.000Z","What We've Learned Updated: Hosts are showing an error stating they could not transfer certificate info. Awaiting log upload from Eric



--------
24/01/2025
--------
Certificate exchange is failing with the service account and falling back to the system account. 
The issue appears similar to 00422068, but in this case both the local system and service accounts are failing

22/01/2025 16:08:23	INFO	StealthAUDIT	THostConnection.GetOrderedSecurityMap	""Following credentials are preferred for the host usilg01-fpt011.wrbts.ads.wrberkley.com in profile ""StealthAUDIT Svc Acct"" : WRBTSsvc-bts-p-slb01 ""			-1	13180	14876
22/01/2025 16:08:23	DEBUG	FILESYSTEMACCESS	AccessScanTask	""Acquiring certificate exchange lock at D:StealthAUDITFSAAfsaa_certificate_exchange.lock""	usilg01-fpt011.wrbts.ads.wrberkley.com	DCExtract	13740	13180	14876
22/01/2025 16:08:23	DEBUG	FILESYSTEMACCESS	AccessScanTask	""Using certificate authority: Friendly Name = FSAA Certificate Authority 7/9/2024 10:37:52 AM, Thumbprint = 120676946BB74ECCCB5656104C484C57707A2E4C""	usilg01-fpt011.wrbts.ads.wrberkley.com	DCExtract	13740	13180	14876
22/01/2025 16:08:23	INFO	FILESYSTEMACCESS	AccessScanTask	""Failed to exchange certificates with running proxy service using task credentials, retrying with LocalSystem: Unable to establish secure stream for certificate exchange, requires trusted target domain""	usilg01-fpt011.wrbts.ads.wrberkley.com	DCExtract	13740	13180	14876
22/01/2025 16:08:23	DEBUG	FILESYSTEMACCESS	AccessScanTask	""Certificate exchange with running proxy service failed: Stealthbits.StealthAUDIT.DataCollectors.FSAA.Applet.Client.AppletClientException: Unable to establish secure stream for certificate exchange, requires trusted target domain ---> System.Security.Authentication.AuthenticationException: A call to SSPI failed, see inner exception. ---> System.ComponentModel.Win32Exception: The target principal name is incorrect     --- End of inner exception stack trace ---     at System.Net.Security.NegoState.StartSendAuthResetSignal(LazyAsyncResult lazyResult, Byte[] message, Exception exception)     at System.Net.Security.NegoState.StartSendBlob(Byte[] message, LazyAsyncResult lazyResult)     at System.Net.Security.NegoState.CheckCompletionBeforeNextSend(Byte[] message, LazyAsyncResult lazyResult)     at System.Net.Security.NegoState.ProcessReceivedBlob(Byte[] message, LazyAsyncResult lazyResult)     at System.Net.Security.NegoState.StartReceiveBlob(LazyAsyncResult lazyResult)     at System.Net.Security.NegoState.CheckCompletionBeforeNextReceive(LazyAsyncResult lazyResult)     at System.Net.Security.NegoState.StartSendBlob(Byte[] message, LazyAsyncResult lazyResult)     at System.Net.Security.NegoState.ProcessAuthentication(LazyAsyncResult lazyResult)     at System.Net.Security.NegotiateStream.AuthenticateAsClient(NetworkCredential credential, ChannelBinding binding, String targetName, ProtectionLevel requiredProtectionLevel,","","","","005Qk000002AJWTIA4","2025-01-24T16:08:54.000Z"
"0D5Qk00000VStHkKAL","500Qk00000KxAUVIA3","TextPost","005Qk000002AJWTIA4","2025-01-24T16:09:12.000Z","Next Steps Updated: Needs T2 review","","","","005Qk000002AJWTIA4","2025-01-24T16:09:12.000Z"
"0D5Qk00000Vg2sRKAR","500Qk00000KxAUVIA3","TextPost","005Qk000002AJWTIA4","2025-01-28T19:06:21.000Z","Next Steps Updated: Awaiting job to run overnight and verify the issue is resolved.","","","","005Qk000002AJWTIA4","2025-01-28T19:06:21.000Z"
"0D5Qk00000Vg2sQKAR","500Qk00000KxAUVIA3","TextPost","005Qk000002AJWTIA4","2025-01-28T19:06:21.000Z","What We've Learned Updated: Hosts are showing an error stating they could not transfer certificate info. Awaiting log upload from Eric



--------
24/01/2025
--------
Certificate exchange is failing with the service account and falling back to the system account. 
The issue appears similar to 00422068, but in this case both the local system and service accounts are failing

22/01/2025 16:08:23	INFO	StealthAUDIT	THostConnection.GetOrderedSecurityMap	""Following credentials are preferred for the host usilg01-fpt011.wrbts.ads.wrberkley.com in profile ""StealthAUDIT Svc Acct"" : WRBTSsvc-bts-p-slb01 ""			-1	13180	14876
22/01/2025 16:08:23	DEBUG	FILESYSTEMACCESS	AccessScanTask	""Acquiring certificate exchange lock at D:StealthAUDITFSAAfsaa_certificate_exchange.lock""	usilg01-fpt011.wrbts.ads.wrberkley.com	DCExtract	13740	13180	14876
22/01/2025 16:08:23	DEBUG	FILESYSTEMACCESS	AccessScanTask	""Using certificate authority: Friendly Name = FSAA Certificate Authority 7/9/2024 10:37:52 AM, Thumbprint = 120676946BB74ECCCB5656104C484C57707A2E4C""	usilg01-fpt011.wrbts.ads.wrberkley.com	DCExtract	13740	13180	14876
22/01/2025 16:08:23	INFO	FILESYSTEMACCESS	AccessScanTask	""Failed to exchange certificates with running proxy service using task credentials, retrying with LocalSystem: Unable to establish secure stream for certificate exchange, requires trusted target domain""	usilg01-fpt011.wrbts.ads.wrberkley.com	DCExtract	13740	13180	14876
22/01/2025 16:08:23	DEBUG	FILESYSTEMACCESS	AccessScanTask	""Certificate exchange with running proxy service failed: Stealthbits.StealthAUDIT.DataCollectors.FSAA.Applet.Client.AppletClientException: Unable to establish secure stream for certificate exchange, requires trusted target domain ---> System.Security.Authentication.AuthenticationException: A call to SSPI failed, see inner exception. ---> System.ComponentModel.Win32Exception: The target principal name is incorrect     --- End of inner exception stack trace ---     at System.Net.Security.NegoState.StartSendAuthResetSignal(LazyAsyncResult lazyResult, Byte[] message, Exception exception)     at System.Net.Security.NegoState.StartSendBlob(Byte[] message, LazyAsyncResult lazyResult)     at System.Net.Security.NegoState.CheckCompletionBeforeNextSend(Byte[] message, LazyAsyncResult lazyResult)     at System.Net.Security.NegoState.ProcessReceivedBlob(Byte[] message, LazyAsyncResult lazyResult)     at System.Net.Security.NegoState.StartReceiveBlob(LazyAsyncResult lazyResult)     at System.Net.Security.NegoState.CheckCompletionBeforeNextReceive(LazyAsyncResult lazyResult)     at System.Net.Security.NegoState.StartSendBlob(Byte[] message, LazyAsyncResult lazyResult)     at System.Net.Security.NegoState.ProcessAuthentication(LazyAsyncResult lazyResult)     at System.Net.Security.NegotiateStream.AuthenticateAsClient(NetworkCredential credential, ChannelBinding binding, String targetName, ProtectionLevel requiredProtectionLevel,

--------
01/28/2025
--------
We changed the jobs to run with a specified service account instead of using the default and the issue appears to have resolved. The job is set back to use all hosts in the host list instead of just problem hosts and is running so we can check back in the morning to make sure the job succeeds.","","","","005Qk000002AJWTIA4","2025-01-28T19:06:21.000Z"
