"Id","CaseNumber","Ticket_Record_Type_Name__c","Subject","Description","DevOps_Steps_to_Reproduce__c","What_We_Know__c","Next_Steps__c","Solution_Comment__c","Issue_Type__c","Ticket_Owner_Name__c","Ticket_Type__c","Platform__c","Collector_Code__c","Feature__c","Product_Version__c","Build_Number__c","Age__c","Status","Account_Name__c","Contact_Name__c","CreatedDate","ClosedDate"
"500Qk00000O6yzpIAB","00442249","Support Ticket","Username Problem - (Koza Halı)","Hello,
I would like to follow up on a previously opened case (Case ID: 00439580). However, when I try to view the details of this case, I encounter a screen and content like the one attached.
Could you please fix this?

Best Regards","","16-04 Customer encounter an issue with his logs, where another user is displayed than the one connected.","16-04 We will schedule a remote session for tomorrow, to check the details .","solved in the remote session.","","Daniel Anton","Question","Netwrix Endpoint Protector","Content-Aware Protection","CAP Policies","","","0.9","Closed - Resolved","Laykon Distributor","Yağız Özkütük","2025-04-16T10:33:14.000Z","2025-04-17T08:45:25.000Z"
