"Id","ParentId","CommentBody","CreatedById","CreatedDate","LastModifiedDate","IsPublished","IsDeleted"
"00aQk000008ha23IAA","500Qk00000D9gDRIAZ","On Escalation Ticket # 00419021 the Following Fields have been updated: 
Priority has been changed to Medium.","005Qk000001nVi2IAE","2024-08-23T16:32:03.000Z","2024-08-23T16:32:03.000Z","false","false"
"00aQk0000093yVVIAY","500Qk00000D9gDRIAZ","On Escalation Ticket # 00419021 the Following Fields have been updated: 
Status has been changed to Awaiting Escalating Engineer.","0054u000006gtWUAAY","2024-09-12T13:48:24.000Z","2024-09-12T13:48:24.000Z","false","false"
"00aQk0000093yVXIAY","500Qk00000D9gDRIAZ","On Escalation Ticket # 00419021 the new comment has been added: Alex Puskas:

@WaitingOnEngineer

The logs contains only 2 minutes and the only important log from file is:


08-23 16:18:12.126 23644 ERROR Â Register request failed. cURL error is: 28, Failed to connect to 34.71.158.218 port 443 after 21029 ms: Timed out, proxy: false [CSoapClient::SendRequest SoapClient.cpp:294]
-> the server is not accessible

This error appears when other vpn/proxy is present and sometimes the mentioned server cannot be access at all even if the user try to access it using the browser.
Few questions:

	 - 	The mentioned url: https://34.71.158.218/index.php can be accessed? (from browser)
	 - 	This is happening only on few computers?

[DevOps CommentId:10918290]","0054u000006gtWUAAY","2024-09-12T13:48:24.000Z","2024-09-12T13:48:24.000Z","false","false"
"00aQk00000940qfIAA","500Qk00000D9gDRIAZ","On Escalation Ticket # 00419021 the Following Fields have been updated: 
Status has been changed to Closed - Resolved.","005Qk000001nViHIAU","2024-09-12T14:09:22.000Z","2024-09-12T14:09:22.000Z","false","false"
"00aQk000009D7XxIAK","500Qk00000D9gDRIAZ","On Escalation Ticket # 00419021 the Following Fields have been updated: 
Status has been changed to Awaiting Escalating Engineer.","0054u000006gtWUAAY","2024-09-20T05:02:17.000Z","2024-09-20T05:02:17.000Z","false","false"
"00aQk000009D7XzIAK","500Qk00000D9gDRIAZ","On Escalation Ticket # 00419021 the new comment has been added: -- DevOps Automation Assistant --

This escalation has been in the status 'Awaiting Support' since 2024-09-12 13:48 UTC and no response has been detected.

If this escalation has been resolved with the customer, please add a comment so this can be closed in Azure DevOps.

@WaitingOnEngineer

[DevOps CommentId:10951177]","0054u000006gtWUAAY","2024-09-20T05:02:17.000Z","2024-09-20T05:02:17.000Z","false","false"
"00aQk000009DCPZIA4","500Qk00000D9gDRIAZ","On Escalation Ticket # 00419021 the Following Fields have been updated: 
Status has been changed to Closed - Resolved.","005Qk000001nViHIAU","2024-09-20T07:34:46.000Z","2024-09-20T07:34:46.000Z","false","false"
