"Id","ParentId","Type","CreatedById","CreatedDate","Body","Title","LinkUrl","RelatedRecordId","InsertedById","LastModifiedDate"
"0D5Qk00000VGcG7KAL","500Qk00000KvlulIAB","TextPost","0054u000008ARZjAAO","2025-01-22T14:36:53.000Z","Description: All Entra collection jobs in EA are failing. FYI... Collections are also failing in Threat Manager. I have verified that the connection profile is current. I have also verified that the Netwrix products are able to successfully connect to our Entra tenant.

Enterprise Auditor error message:
PrepareTask for DC 'AZUREADINVENTORY' for task 'AAD Inventory' failed: Unspecified error","","","","0054u000008ARZjAAO","2025-01-22T14:36:53.000Z"
"0D5Qk00000VIz8SKAT","500Qk00000KvlulIAB","TextPost","0054u000007MiY9AAK","2025-01-22T16:50:19.000Z","<p>Debug logs would definitely help here! Also, is this a new setup or did it stop working recently?</p>","","","","0054u000007MiY9AAK","2025-01-22T16:50:19.000Z"
"0D5Qk00000VNzQwKAL","500Qk00000KvlulIAB","TextPost","0054u000007oss5AAA","2025-01-23T13:53:48.000Z","Next Steps Updated: review the logs provided","","","","0054u000007oss5AAA","2025-01-23T13:53:48.000Z"
"0D5Qk00000VNzQvKAL","500Qk00000KvlulIAB","TextPost","0054u000007oss5AAA","2025-01-23T13:53:48.000Z","What We've Learned Updated: Client has had Entra jobs enabled since implantation, but only recently started to look at the jobs. 
The errors have likely been there the entire time, just unnoticed","","","","0054u000007oss5AAA","2025-01-23T13:53:48.000Z"
"0D5Qk00000VPy7IKAT","500Qk00000KvlulIAB","TextPost","0054u000007oss5AAA","2025-01-23T20:38:51.000Z","Invitation updated. Attendees: No attendees listed","","","","0054u000007oss5AAA","2025-01-23T20:38:51.000Z"
"0D5Qk00000VPy7JKAT","500Qk00000KvlulIAB","TextPost","0054u000007oss5AAA","2025-01-23T20:38:52.000Z","Invitation updated. Attendees: Joshua Sexton","","","","0054u000007oss5AAA","2025-01-23T20:38:52.000Z"
"0D5Qk00000VPy7KKAT","500Qk00000KvlulIAB","TextPost","0054u000007oss5AAA","2025-01-23T20:38:52.000Z","Invitation updated. Attendees: Joshua Sexton, James Rigoulot","","","","0054u000007oss5AAA","2025-01-23T20:38:52.000Z"
"0D5Qk00000VSGd9KAH","500Qk00000KvlulIAB","TextPost","0054u000007oss5AAA","2025-01-24T13:31:09.000Z","Description Updated: All Entra collection jobs in EA are failing. FYI... Collections are also failing in Threat Manager. I have verified that the connection profile is current. I have also verified that the Netwrix products are able to successfully connect to our Entra tenant.

Enterprise Auditor error message:
PrepareTask for DC 'AZUREADINVENTORY' for task 'AAD Inventory' failed: Unspecified error

---------------
current error:
""ExecuteScalar requires an open and available Connection. The connection's current state is closed.""","","","","0054u000007oss5AAA","2025-01-24T13:31:09.000Z"
"0D5Qk00000VSXyTKAX","500Qk00000KvlulIAB","TextPost","0054u000007oss5AAA","2025-01-24T13:35:51.000Z","What We've Learned Updated: Client has had Entra jobs enabled since implantation, but only recently started to look at the jobs. 
The errors have likely been there the entire time, just unnoticed

---------------
secret was expired causing access denied
that's been fixed and now getting what looks like a SQL error:

""ExecuteScalar requires an open and available Connection. The connection's current state is closed.""

I'm not seeing this error in sales force
---------------","","","","0054u000007oss5AAA","2025-01-24T13:35:51.000Z"
"0D5Qk00000VSXyUKAX","500Qk00000KvlulIAB","TextPost","0054u000007oss5AAA","2025-01-24T13:35:51.000Z","Next Steps Updated: ask for fresh debug logs again","","","","0054u000007oss5AAA","2025-01-24T13:35:51.000Z"
"0D5Qk00000VSO7SKAX","500Qk00000KvlulIAB","TextPost","0054u000007oss5AAA","2025-01-24T13:43:55.000Z","What We've Learned Updated: Client has had Entra jobs enabled since implantation, but only recently started to look at the jobs. 
The errors have likely been there the entire time, just unnoticed

---------------
secret was expired causing access denied
that's been fixed and now getting what looks like a SQL error:

""ExecuteScalar requires an open and available Connection. The connection's current state is closed.""

I'm not seeing this error in sales force

the AAD_scan doens't use a bulk import job to upload to SQL. I'm assuming it writes straight to sql, but I don't knwo

---------------","","","","0054u000007oss5AAA","2025-01-24T13:43:55.000Z"
"0D5Qk00000VeSWpKAN","500Qk00000KvlulIAB","TextPost","0054u000007oss5AAA","2025-01-28T13:42:55.000Z","Next Steps Updated: discussing with T2","","","","0054u000007oss5AAA","2025-01-28T13:42:55.000Z"
"0D5Qk00000VeHzlKAF","500Qk00000KvlulIAB","TextPost","0054u000007oss5AAA","2025-01-28T13:44:38.000Z","What We've Learned Updated: Client has had Entra jobs enabled since implantation, but only recently started to look at the jobs. 
The errors have likely been there the entire time, just unnoticed

---------------
secret was expired causing access denied
that's been fixed and now getting what looks like a SQL error:

""ExecuteScalar requires an open and available Connection. The connection's current state is closed.""

I'm not seeing this error in sales force

the AAD_scan doens't use a bulk import job to upload to SQL. I'm assuming it writes straight to sql, but I don't knwo

---------------

looking at the full error, it looks like a SQL timeout issue","","","","0054u000007oss5AAA","2025-01-28T13:44:38.000Z"
"0D5Qk00000VeJtYKAV","500Qk00000KvlulIAB","TextPost","0054u000007oss5AAA","2025-01-28T13:51:25.000Z","What We've Learned Updated: Client has had Entra jobs enabled since implantation, but only recently started to look at the jobs. 
The errors have likely been there the entire time, just unnoticed

---------------
secret was expired causing access denied
that's been fixed and now getting what looks like a SQL error:

""ExecuteScalar requires an open and available Connection. The connection's current state is closed.""

I'm not seeing this error in sales force

the AAD_scan doens't use a bulk import job to upload to SQL. I'm assuming it writes straight to sql, but I don't knwo

---------------

looking at the full error, it looks like a SQL timeout issue
The job task table reads like it times out at 18 minutes everytime

27/01/2025 08:21:37    ERROR    AZUREADINVENTORY    Stealthbits.StealthAUDIT.DataCollectors.AzureADInventory.Tasks.AADInventoryScanTask.InternalProcessRecord    ""System.InvalidOperationException: ExecuteScalar requires an open and available Connection. The connection's current state is closed.     at System.Data.SqlClient.SqlCommand.ValidateCommand(String method, Boolean async)     at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)     at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)     at System.Data.SqlClient.SqlCommand.ExecuteScalar()     at Stealthbits.StealthAUDIT.DataCollectors.AzureADInventory.Database.AADInventoryDatabaseUpdate.CalculateEffectiveGroupMembership(Action`1 taskStatus)     at Stealthbits.StealthAUDIT.DataCollectors.AzureADInventory.Database.AADInventoryDatabaseUpdate.FinalizeScan(Action`1 taskStatus)     at Stealthbits.StealthAUDIT.DataCollectors.AzureADInventory.Database.AADInventoryDatabaseUpdate.Finish(Action`1 taskStatus)     at Stealthbits.StealthAUDIT.DataCollectors.AzureADInventory.Tasks.AADInventoryScanTask.InternalProcessRecord()""    MOTIVALLC.ONMICROSOFT.COM    DCExtract    10828    9824    10992","","","","0054u000007oss5AAA","2025-01-28T13:51:25.000Z"
"0D5Qk00000VeOKMKA3","500Qk00000KvlulIAB","TextPost","0054u000007oss5AAA","2025-01-28T14:50:40.000Z","What We've Learned Updated: Client has had Entra jobs enabled since implantation, but only recently started to look at the jobs. 
The errors have likely been there the entire time, just unnoticed

---------------
secret was expired causing access denied
that's been fixed and now getting what looks like a SQL error:

""ExecuteScalar requires an open and available Connection. The connection's current state is closed.""

I'm not seeing this error in sales force

the AAD_scan doens't use a bulk import job to upload to SQL. I'm assuming it writes straight to sql, but I don't knwo

---------------

looking at the full error, it looks like a SQL timeout issue
The job task table reads like it times out at 18 minutes everytime

27/01/2025 08:21:37    ERROR    AZUREADINVENTORY    Stealthbits.StealthAUDIT.DataCollectors.AzureADInventory.Tasks.AADInventoryScanTask.InternalProcessRecord    ""System.InvalidOperationException: ExecuteScalar requires an open and available Connection. The connection's current state is closed.     at System.Data.SqlClient.SqlCommand.ValidateCommand(String method, Boolean async)     at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)     at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)     at System.Data.SqlClient.SqlCommand.ExecuteScalar()     at Stealthbits.StealthAUDIT.DataCollectors.AzureADInventory.Database.AADInventoryDatabaseUpdate.CalculateEffectiveGroupMembership(Action`1 taskStatus)     at Stealthbits.StealthAUDIT.DataCollectors.AzureADInventory.Database.AADInventoryDatabaseUpdate.FinalizeScan(Action`1 taskStatus)     at Stealthbits.StealthAUDIT.DataCollectors.AzureADInventory.Database.AADInventoryDatabaseUpdate.Finish(Action`1 taskStatus)     at Stealthbits.StealthAUDIT.DataCollectors.AzureADInventory.Tasks.AADInventoryScanTask.InternalProcessRecord()""    MOTIVALLC.ONMICROSOFT.COM    DCExtract    10828    9824    10992

---------------
Searching the internet I can only find examples of this error caused by coding issues. This will likey need escalating.","","","","0054u000007oss5AAA","2025-01-28T14:50:40.000Z"
"0D5Qk00000VewJeKAJ","500Qk00000KvlulIAB","TextPost","0054u000007oss5AAA","2025-01-28T16:25:00.000Z","Next Steps Updated: request another debug log run of the job","","","","0054u000007oss5AAA","2025-01-28T16:25:00.000Z"
"0D5Qk00000VemEaKAJ","500Qk00000KvlulIAB","TextPost","0054u000007oss5AAA","2025-01-28T16:27:14.000Z","What We've Learned Updated: Client has had Entra jobs enabled since implantation, but only recently started to look at the jobs. 
The errors have likely been there the entire time, just unnoticed

---------------
secret was expired causing access denied
that's been fixed and now getting what looks like a SQL error:

""ExecuteScalar requires an open and available Connection. The connection's current state is closed.""

I'm not seeing this error in sales force

the AAD_scan doens't use a bulk import job to upload to SQL. I'm assuming it writes straight to sql, but I don't knwo

---------------

looking at the full error, it looks like a SQL timeout issue
The job task table reads like it times out at 18 minutes everytime

27/01/2025 08:21:37    ERROR    AZUREADINVENTORY    Stealthbits.StealthAUDIT.DataCollectors.AzureADInventory.Tasks.AADInventoryScanTask.InternalProcessRecord    ""System.InvalidOperationException: ExecuteScalar requires an open and available Connection. The connection's current state is closed.     at System.Data.SqlClient.SqlCommand.ValidateCommand(String method, Boolean async)     at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)     at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)     at System.Data.SqlClient.SqlCommand.ExecuteScalar()     at Stealthbits.StealthAUDIT.DataCollectors.AzureADInventory.Database.AADInventoryDatabaseUpdate.CalculateEffectiveGroupMembership(Action`1 taskStatus)     at Stealthbits.StealthAUDIT.DataCollectors.AzureADInventory.Database.AADInventoryDatabaseUpdate.FinalizeScan(Action`1 taskStatus)     at Stealthbits.StealthAUDIT.DataCollectors.AzureADInventory.Database.AADInventoryDatabaseUpdate.Finish(Action`1 taskStatus)     at Stealthbits.StealthAUDIT.DataCollectors.AzureADInventory.Tasks.AADInventoryScanTask.InternalProcessRecord()""    MOTIVALLC.ONMICROSOFT.COM    DCExtract    10828    9824    10992

---------------
Searching the internet I can only find examples of this error caused by coding issues. This will likely need escalating.

discussed over TKS
need to gather another run with debug logs.
it looks to be failing after trying to switch to group membership but it's also only getting to users letter R","","","","0054u000007oss5AAA","2025-01-28T16:27:14.000Z"
"0D5Qk00000XG6q4KAD","500Qk00000KvlulIAB","TextPost","0054u000006gpoAAAQ","2025-02-18T22:48:14.000Z","Invitation updated. Attendees: Nicholas Zimmer","","","","0054u000006gpoAAAQ","2025-02-18T22:48:14.000Z"
"0D5Qk00000XG6q5KAD","500Qk00000KvlulIAB","TextPost","0054u000006gpoAAAQ","2025-02-18T22:48:14.000Z","Invitation updated. Attendees: Nicholas Zimmer, James Rigoulot","","","","0054u000006gpoAAAQ","2025-02-18T22:48:14.000Z"
