"Id","CaseNumber","Ticket_Record_Type_Name__c","Subject","Description","DevOps_Steps_to_Reproduce__c","What_We_Know__c","Next_Steps__c","Solution_Comment__c","Issue_Type__c","Ticket_Owner_Name__c","Ticket_Type__c","Platform__c","Collector_Code__c","Feature__c","Product_Version__c","Build_Number__c","Age__c","Status","Account_Name__c","Contact_Name__c","CreatedDate","ClosedDate"
"500Qk00000FpHPeIAN","00421137","Support Ticket","POC: NEA FSAA JOB Scan Error","The FSAA Scan is not completing due to an internal error.  PLease see error below 

System.Net.WebException: The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel. ---> System.Security.Authentication.AuthenticationException: The remote certificate is invalid according to the validation procedure.     at System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)     at System.Net.PooledStream.EndWrite(IAsyncResult asyncResult)     at System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)     --- End of inner exception stack trace ---     at System.Net.HttpWebRequest.EndGetRequestStream(IAsyncResult asyncResult, TransportContext& context)     at System.Net.Http.HttpClientHandler.GetRequestStreamCallback(IAsyncResult ar)     --- End of inner exception stack trace ---     at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)     at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)     at Stealthbits.StealthAUDIT.DataCollectors.FSAA.Applet.Client.HttpsClient.<SendRequestAsync>d__33.MoveNext()  --- End of stack trace from previous location where exception was thrown ---     at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)     at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)     at Stealthbits.StealthAUDIT.DataCollectors.FSAA.Applet.Client.HttpsClient.<InitializeScanSessionAsync>d__13.MoveNext()  --- End of stack trace from previous location where exception was thrown ---     at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)     at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)     at Stealthbits.StealthAUDIT.DataCollectors.FSAA.AppletDeployment.<StartScanSessionAsync>d__35.MoveNext()  --- End of stack trace from previous location where exception was thrown ---     at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)     at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)     at Stealthbits.StealthAUDIT.DataCollectors.FSAA.Util.<>c__DisplayClass25_0.<<RetryTaskWithTimeLimit>b__0>d.MoveNext()  --- End of stack trace from previous location where exception was thrown ---     at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)     at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)     at Stealthbits.StealthAUDIT.DataCollectors.FSAA.Util.<>c__DisplayClass26_0`1.<RetryTaskWithTimeLimit>b__0()     at Stealthbits.StealthAUDIT.DataCollectors.FSAA.Util.RetryWithTimeLimit[TResult](TimeSpan timeLimit, TimeSpan retryDelay, Func`1 func, Log log, Func`2 shouldRetryFunc)     --- End of inner exception stack trace ---     at Stealthbits.StealthAUDIT.DataCollectors.FSAA.Util.RetryWithTimeLimit[TResult](TimeSpan timeLimit, TimeSpan retryDelay, Func`1 func, Log log, Func`2 shouldRetryFunc)     at Stealthbits.StealthAUDIT.DataCollectors.FSAA.Util.RetryTaskWithTimeLimit[TResult](TimeSpan timeLimit, TimeSpan retryDelay, Func`1 func, Log log, Func`2 shouldRetryFunc)     at Stealthbits.StealthAUDIT.DataCollectors.FSAA.Util.RetryTaskWithTimeLimit(TimeSpan timeLimit, TimeSpan retryDelay, Func`1 func, Log log, Func`2 shouldRetryFunc)     at Stealthbits.StealthAUDIT.DataCollectors.FSAA.ScanTaskBase.StartScanSession(String execHost, Int32 endPoint, Int32 certificateExchangePort, AppletPriority appletPriority, FSAAConfigType configXML)     at Stealthbits.StealthAUDIT.DataCollectors.FSAA.ScanTaskBase.StartScanSessionWithRetry(String execHost, Int32 endPoint, Int32 certificateExchangePort, AppletPriority appletPriority, FSAAConfigType configXML)     at Stealthbits.StealthAUDIT.DataCollectors.FSAA.AccessScanTask.<InternalProcessRecordAsync>d__2.MoveNext()""	NHDBFSRV1	DCExtract	3608	10284	9352
16/09/2024 15:33:05	ERROR	FILESYSTEMACCESS	Stealthbits.StealthAUDIT.DataCollectors.Tasks.Task.StartExecute	""Stealthbits.StealthAUDIT.DataCollectors.FSAA.FSAAException: Unable to start scan: An error occurred while sending the request.     at Stealthbits.StealthAUDIT.DataCollectors.FSAA.AccessScanTask.<InternalProcessRecordAsync>d__2.MoveNext()  --- End of stack trace from previous location where exception was thrown ---     at","","","","Issue
The FSAA Scan is not completing due to an internal error. PLease see error below

System.Net.WebException: The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel. ---> System.Security.Authentication.AuthenticationException: The remote certificate is invalid according to the validation procedure. at

Cause
Root Cause Unknown.

Resolution
Upgraded to latest version and restarted NEA server.","Root Cause Unknown","Damir Akhmatshin","","Netwrix Enterprise Auditor","StealthAUDIT for Windows File Systems","Data Collection","11.6","90","14.8","Closed - Resolved","Bank AlJazira","Mark Richmond","2024-09-16T16:00:21.000Z","2024-10-01T12:01:05.000Z"
